config/routes.rb
LearnApp::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :admin
  resources :relationships, only: [:create, :destroy, :index]
  resources :carts, only: [:create, :destroy]
  resources :prerequisites, only: :create
  resources :registrations, only: [:create, :destroy]
  resources :courseregistrations, only: [:create, :destroy]
  resources :exams
  resources :questions
  resources :answers
  resources :examresults
  resources :courseratings
  resources :programratings
  resources :categories
  resources :courses do
    member do
      get :programs, :followers, :wants, :wantpros, :notes, :newexam
    end
  end
  resources :users do
    member do
      get :takenprogs, :students, :coursefollows
    end
  end
  resources :programs do
    member do
      get :courses, :wants, :required_courses, :students, :prereq_tree
      put :destroycourse
    end
    collection do
      get :prerequisites, :removeprerequisites
    end
  end
  resources :notes do
    member {get 'download'}
  end

  root to: "static_pages#home"
  match '/admin/add_number', to: "admin#add_number"
  match '/numberusers',   to: "static_pages#latest_number_users"
  match '/addcourses',    to: "programs#addcourses"
  match '/viewfile',      to: "notes#view"
  match '/passcourse',    to: "courses#passcourse"
  match '/moveupcourse',  to: "courses#listorder_up"
  match '/movedowncourse',to: "courses#listorder_down"
  match '/moveupexam',    to: "exams#listorder_up"
  match '/movedownexam',  to: "exams#listorder_down"
  match '/cart',          to: "users#cart"
  match '/programs',      to: "programs#index"
  match '/newprogram',    to: "programs#new"
  match '/newexam',       to: "exams#new"
  match '/courses',       to: "courses#index"
  match '/creations',     to: "users#creations"
  match '/newcourse',     to: "courses#new"
  match '/search',        to: "search#index"
  match '/database',      to: "admin#database"
  match '/addcategory',   to: "admin#addcategory"
  match '/signup',        to: "users#new"
  match '/signin',        to: "sessions#new"
  match '/signout',       to: "sessions#destroy", via: :delete
  match '/about',         to: "static_pages#about"
  match '/help',          to: "static_pages#help"
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @total = User.all.count
  	if signed_in?
  		@user = current_user
  		@categories = Category.order_by('title ASC').all
    else
      @home_page = true
  	end
  end

  def about
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_unsigned.html.erb
<div class="homehome home_1">
	<div class="home_cont1"> 
		<div class="homepage-main1">
			<p>Welcome to Learnocracy.</p>
			<!--<p>
				There are currently <%= @total %> users signed up!
			</p>-->
			<p>
				A place to teach and learn anything and everything.
			</p>
			<p>
				<%= link_to "Sign up now!", signup_path %>
			</p>
		</div>
	</div>
</div>
<div class="homehome home_2">
	<div class="home_cont2"> 
		<div class="homepage-main2">
			<p>
				How it works
			</p>
			<p>
				There are 2 main uses for this site. Learning and Teaching.
			</p>
			<p>
				Those who want to learn will have access to a vast selection of courses and entire curriculums in all fields.
			</p>
			<p>
				Courses will consist of material, in either readable or viewable form, and exams, that will test your knowledge, allowing you to follow the progress you're making.
			</p>
			<p>
				The curriculums are entire programs built as sets of courses. Requirements between courses will be made, which will allow the student to follow a clear path. A prerequisite tree will be available for all programs, where you will be able to see which classes oyu have passed, which ones you can take, and which ones are too complicated for the moment. Once all are completed, the user should have acquired the knowledge equivalent to that of a degree.
			</p>
			<p>
				Finally, these programs will have been created by both teachers and regular people.
			</p>
		</div>
	</div>
</div>
<div class="homehome home_3">
	<div class="home_cont3"> 
		<div class="homepage-main3">
			<p>
				For those of you who want to create the material or programs, this is how it works.
			</p>
			<p>
				Those who create courses will be able to create notes as PDFs, PPTs or youtube videos, all three of which will be embed within the site. Then, you will have the possibility to create quizzes or exams, at which point you will set the minimum grade required to pass and set up the questions and answers (only as multiple choice for now). At any point in time, the students will be allowed to take the tests and try to pass the exam. Once all tests passed, they will pass the course.
			</p>
			<p>
				To create a program, you don't have to have created any course. You will gather a set of courses deemed appropriate for your program, and then set the prerequisites among them. The set of prerequisites will automatically create a prerequisite tree, which will allow the user to follow an obvious path for progress.
			</p>
		</div>
	</div>
</div>

app/views/static_pages/_user_home.html.erb
<% provide(:title, "Home Page") %>
<div class="homepage-list">
	<h1>The Different Fields</h1>
	<% @categories.each do |cat| %>
	<%= link_to category_path(cat) do %>
		<div class="course-list-2">
			<div class="category-image-2">
				<img src="data:<%= cat.imagetype %>;base64,<%= cat.image.to_s %>" />
			</div>
			<div class="cours-cont">
				<h2><%= cat.title %></h2>
				<div class="home-cour-list">Number of Programs: <%= cat.numprog %></div>
				<div>Number of Courses: <%= cat.numcour %></div>
			</div>
		</div>
		<% end %>
	<% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<span>About</span>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<%= render 'user_home' %>
<% else %>
	<%= render 'home_unsigned' %>
<% end %>