config/routes.rb
LearnApp::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :admin
  resources :relationships, only: [:create, :destroy, :index]
  resources :carts, only: [:create, :destroy]
  resources :prerequisites, only: :create
  resources :registrations, only: [:create, :destroy]
  resources :courseregistrations, only: [:create, :destroy]
  resources :exams
  resources :questions
  resources :answers
  resources :examresults
  resources :courseratings
  resources :programratings
  resources :categories
  resources :courses do
    member do
      get :programs, :followers, :wants, :wantpros, :notes, :newexam
    end
  end
  resources :users do
    member do
      get :takenprogs, :students, :coursefollows
    end
  end
  resources :programs do
    member do
      get :courses, :wants, :required_courses, :students, :prereq_tree
      put :destroycourse
    end
    collection do
      get :prerequisites, :removeprerequisites
    end
  end
  resources :notes do
    member {get 'download'}
  end

  root to: "static_pages#home"
  match '/admin/add_number', to: "admin#add_number"
  match '/numberusers',   to: "static_pages#latest_number_users"
  match '/addcourses',    to: "programs#addcourses"
  match '/viewfile',      to: "notes#view"
  match '/passcourse',    to: "courses#passcourse"
  match '/moveupcourse',  to: "courses#listorder_up"
  match '/movedowncourse',to: "courses#listorder_down"
  match '/moveupexam',    to: "exams#listorder_up"
  match '/movedownexam',  to: "exams#listorder_down"
  match '/cart',          to: "users#cart"
  match '/programs',      to: "programs#index"
  match '/newprogram',    to: "programs#new"
  match '/newexam',       to: "exams#new"
  match '/courses',       to: "courses#index"
  match '/creations',     to: "users#creations"
  match '/newcourse',     to: "courses#new"
  match '/search',        to: "search#index"
  match '/database',      to: "admin#database"
  match '/addcategory',   to: "admin#addcategory"
  match '/signup',        to: "users#new"
  match '/signin',        to: "sessions#new"
  match '/signout',       to: "sessions#destroy", via: :delete
  match '/about',         to: "static_pages#about"
  match '/help',          to: "static_pages#help"
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :filename, :contenttype, :file_title
  belongs_to :course
  acts_as_list scope: :course

  validates :course_id, presence: true
  validates :content, presence: true
  validates :filename, presence: true
  validates :contenttype, presence: true
  validates :file_title, presence: true

  def as_file
  	output = Base64.decode64(self.content)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :signed_in_user, except: [:view, :show]
  before_filter :course_creator, only: :create
  before_filter :note_creator, only: [:destroy, :listorder_up, :listorder_down]

  def create
    @course = Course.find(params[:note][:id])
    @error = 0
    @errors = []
    @position = @course.notes.count
    if params[:note].has_key?(:youtube)
        @link = params[:note][:content].match(/\/watch.*/)[0][9..-1]
        @note = @course.notes.build(:position => @position,:content => @link, :file_title => params[:note][:file_title], :filename => params[:note][:content], :contenttype => "youtube")
    else
        params[:note][:content].tempfile = Base64.encode64(open(params[:note][:content].tempfile).to_a.join)
        params[:note][:filename] = params[:note][:content].original_filename
        params[:note][:contenttype] = params[:note][:content].content_type
        @note = @course.notes.build(:position => @position, :content => params[:note][:content].tempfile, :file_title => params[:note][:file_title], :filename => params[:note][:filename], :contenttype => params[:note][:contenttype])
    end
    if @errors.any?
      if @error == 1
        redirect_to edit_course_path(@course, :errors => @errors, :youtuber => "yes")
      else
        redirect_to edit_course_path(@course, :errors => @errors)
      end
    else
      if @note.save
        @notes = @course.notes
        render "note_create_js", :locals => {:@notes1 => @notes, :@course_id1 => @course.id, :@course1 => @course}
      else
        render root_path
      end
    end
  end

  def view
    @note = Note.find(params[:id])
    @course = @note.course
    if @note.contenttype == "youtube"
      @url = "http://www.youtube.com/embed/" + @note.content
      @video = "yes"
    else
      @url = "http://docs.google.com/gview?url=http://learnocracy.herokuapp.com/notes/" + params[:id] + "&embedded=true"
      @video = "no"
    end
  end

  def update
    @note = Note.find(params[:id])
    @course_id = @note.course_id
    @course = Course.find(@course_id)
    @notes = @course.notes
    if(params.has_key?(:note))
      @move = params[:note][:move]
      if(@move=="0")
        @note.move_lower
      else
        @note.move_higher
      end
      render :template => "notes/destroy_js", :locals => {:@notes => @notes, :@course_id => @course_id}
    end
  end

  def show
    note = Note.find(params[:id])
    send_data note.as_file,
      :filename => note.filename,
      :type => note.contenttype,
      :disposition => "inline",
      :file_title => note.file_title
  end

  def download
    note = Note.find(params[:id])
    send_data note.as_file,
      :filename => note.filename,
      :type => note.contenttype
  end

  def destroy
    note = Note.find(params[:id])
    @course = Course.find(note.course_id)
    note.remove_from_list
    if note.destroy
      @notes = @course.notes
      @course_id = @course.id
      render :template => "notes/destroy_js", :locals => {:@notes => @notes, :@course_id => @course_id}
    end
  end

  private
    def note_creator
      redirect_to root_path unless des_note?
    end

    def course_creator
      redirect_to root_path unless note_creator?
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_note.html.erb
<% @notes.each do |note| %>
	<% if !note.filename.nil? %>
	<li>
		<% if @see_exam %>
			<% if note.contenttype == "application/pdf" or note.contenttype == "youtube" %>
				<span class="content">
					<% if params.has_key?(:program) %>
						<%= link_to note.file_title, viewfile_path(id: note.id, program: @program.id) %>
					<% else %>
						<%= link_to note.file_title, viewfile_path(id: note.id) %>
					<% end %>
				</span>
			<% else %>
				<span class="content">
					<%= note.file_title %>
				</span>
			<% end %>
			<% if note.contenttype != "youtube" %>
			<span class="smaller">
				<% if note.content.length/1.3572/1000 > 1000 %>
					<%= ((note.content.length/1.3572)/1000000).round(1) %>MB
				<% else %>
					<%= ((note.content.length/1.3572)/1000).round %>KB
				<% end %>
			</span>
			<span class="smaller note-dwn">
				<%= link_to "Download", download_note_path(note) %>
			</span>
			<% else %>
				<span class="smaller">
					 VIDEO
				</span>
			<% end %>
		<% else %>
		<span class="unclickable-file">
			<span class="content">
				<%= note.file_title %>
			</span>
			<% if note.contenttype == "youtube" %>
				<span class="smaller">
						 VIDEO
				</span>
			<% end %>
		</span>
		<% end %>
	</li>
	<% end %>
<% end %>

app/views/notes/_note_form.html.erb
<%= form_for(@course.notes.build, :remote => true) do |f| %>
	<%= render 'shared/error_messages', object: f.object, :html => { :id => "myform" } %>
	<%= f.hidden_field :id, :value => @course_id %>
	<%= f.label "Create File" %>
	<div>
	<%= f.label "File title : " %>
	<%= f.text_field :file_title, class: "course-edit-field" %>
	</div>
	<div>
	<%= f.file_field :content, :html => { :id => "myfile" } %>
	</div>
	<%= f.submit "Upload File", class: "subcon note-submit", :disable_with => "Uploading…" %>
<% end %>

app/views/notes/_note_list.html.erb
<% @notes.each_with_index do |note, i| %>
	<% if !note.filename.nil? %>
	<li class="one_file">
	<%= form_for(note, :remote => true) do |f| %>
  		<%= f.hidden_field :move, :value => "1" %>
  		<%= f.submit "", :type => :image, :src => "/assets/arrow-up.png", :class => "list_arrow1" %>
	<% end %>
	<%= form_for(note, :remote => true) do |f| %>
  		<%= f.hidden_field :move, :value => "0" %>
  		<%= f.submit "", :type => :image, :src => "/assets/arrow-down.png", :class => "list_arrow1" %>
	<% end %>
	<%= i+1 %>.
	<% if note.contenttype == "application/pdf" or note.contenttype == "youtube" %>
		<span class="content">
			<%= link_to note.file_title, viewfile_path(id: note.id) %>
		</span>
	<% else %>
		<span class="content">
			<%= note.file_title %>
		</span>
	<% end %>
	<% if note.contenttype == "youtube" %>
		<span class="smaller">
			 VIDEO
		</span>
	<% end %>
	<span class="delete-btn">
		<%= link_to "Delete", note_path(:id => note.id),
										method: :delete,
										title: note.filename,
										:remote => true %>
	</span>
	</li>
	<% end %>
<% end %>

app/views/notes/create.js.erb
$("#note_edit_form").html("<%= escape_javascript (render :partial => 'courses/note_form', :locals => {:@new_note => @new_note, :@course_id => @course_id, :@course => @course} ) %>");
$("#list_note_det").html("<%= escape_javascript (render :partial => 'notes/note_list', :locals => {:@notes => @notes, :@course_id => @course_id} ) %>");

app/views/notes/destroy.js.erb
$("#note_list_det").html("<%= escape_javascript (render :partial => 'notes/note_list', :locals => {:@notes => @notes, :@course_id => @course_id} ) %>");

app/views/notes/destroy_js.js.erb
$("#list_note_det").html("<%= escape_javascript (render :partial => 'notes/note_list', :locals => {:@notes => @notes, :@course_id => @course_id} ) %>");

app/views/notes/edit_notes.js.erb
$("#note_edit_form").html("<%= escape_javascript (render :partial => 'courses/note_form', :locals => {:@course_id => @course_id, :@course => @course} ) %>");

app/views/notes/new_notes_j.js.erb
$("#note_edit_form").html("<%= escape_javascript (render :partial => 'courses/note_form', :locals => {:@course_id => @course_id, :@course => @course} ) %>");
$("#list_note_det").html("<%= escape_javascript (render :partial => 'notes/note_list', :locals => {:@notes => @notes, :@course_id => @course_id} ) %>");

app/views/notes/note_create_js.js.erb
$("#list_note_det").html("<%= escape_javascript (render :partial => 'notes/note_list', :locals => {:@notes => @notes1, :@course_id => @course_id1} ) %>");
$("#note_edit_form").html("<%= escape_javascript (render :partial => 'notes/note_form', :locals => {:@course_id => @course_id1, :@course => @course1} ) %>");

app/views/notes/pdf.html.erb
<% provide(:title, note.file_title) %>
<%= note.filename %>

app/views/notes/view.html.erb
<% provide(:title, @note.filename) %>
<div>
	<% if params.has_key?(:program) %>
		<%= link_to "Return to course", course_path(@course, :program => params[:program]) %>
	<% else %>
		<%= link_to "Return to course", course_path(@course) %>
	<% end %>
</div>
<div class="pdf-title"><%= @note.file_title %></div>
<div class="pdf-placement">
	<% if @video == "yes" %>
	<iframe src="<%= @url %>" class="video-viewer" frameborder="0"></iframe>
	<% else %>
	<div class="pdf-border"></div>
	<iframe src="<%= @url %>" class="pdf-viewer" frameborder="0"></iframe>
	<% end %>
</div>