config/routes.rb
LearnApp::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :admin
  resources :relationships, only: [:create, :destroy, :index]
  resources :carts, only: [:create, :destroy]
  resources :prerequisites, only: :create
  resources :registrations, only: [:create, :destroy]
  resources :courseregistrations, only: [:create, :destroy]
  resources :exams
  resources :questions
  resources :answers
  resources :examresults
  resources :courseratings
  resources :programratings
  resources :categories
  resources :courses do
    member do
      get :programs, :followers, :wants, :wantpros, :notes, :newexam
    end
  end
  resources :users do
    member do
      get :takenprogs, :students, :coursefollows
    end
  end
  resources :programs do
    member do
      get :courses, :wants, :required_courses, :students, :prereq_tree
      put :destroycourse
    end
    collection do
      get :prerequisites, :removeprerequisites
    end
  end
  resources :notes do
    member {get 'download'}
  end

  root to: "static_pages#home"
  match '/admin/add_number', to: "admin#add_number"
  match '/numberusers',   to: "static_pages#latest_number_users"
  match '/addcourses',    to: "programs#addcourses"
  match '/viewfile',      to: "notes#view"
  match '/passcourse',    to: "courses#passcourse"
  match '/moveupcourse',  to: "courses#listorder_up"
  match '/movedowncourse',to: "courses#listorder_down"
  match '/moveupexam',    to: "exams#listorder_up"
  match '/movedownexam',  to: "exams#listorder_down"
  match '/cart',          to: "users#cart"
  match '/programs',      to: "programs#index"
  match '/newprogram',    to: "programs#new"
  match '/newexam',       to: "exams#new"
  match '/courses',       to: "courses#index"
  match '/creations',     to: "users#creations"
  match '/newcourse',     to: "courses#new"
  match '/search',        to: "search#index"
  match '/database',      to: "admin#database"
  match '/addcategory',   to: "admin#addcategory"
  match '/signup',        to: "users#new"
  match '/signin',        to: "sessions#new"
  match '/signout',       to: "sessions#destroy", via: :delete
  match '/about',         to: "static_pages#about"
  match '/help',          to: "static_pages#help"
  

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :short_desc, :description, :title, :average_rating, :num_rating, :rating_algo, :category
  belongs_to :user
  has_many :relationships, foreign_key: "program_id", dependent: :destroy
  has_many :courses, order: :position, through: :relationships, source: :course
  has_many :wants, through: :prerequisites, source: :want
  has_many :required_courses, through: :prerequisites, source: :required
  has_many :prerequisites, foreign_key: "wantpro_id", dependent: :destroy
  has_many :students, through: :reverse_registrations, source: :student
  has_many :reverse_registrations, foreign_key: "takenprog_id", class_name: "Registration", dependent: :destroy
  has_many :programratings, dependent: :destroy
  has_many :ratings, through: :programratings, source: :program
  has_many :review_titles, through: :programratings, source: :program
  has_many :review_contents, through: :programratings, source: :program
  has_many :completeprograms, dependent: :destroy

  validates :user_id, presence: true
  validates :description, presence: true
  validates :title, presence: true
  validates :short_desc, presence: true, length: { maximum: 300 }
  validates :average_rating, :numericality => {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 5}
  validates :rating_algo, :numericality => {:integer => true}

  def makeprerequisite!(course1, course2)
    prerequisites.create!(required_id: course2.id, want_id: course1.id)
  end

  def hasrating?(user)
    programratings.find_by_user_id(user.id)
  end

  def createrating!(user, rating)
    programratings.create!(user_id: user.id, rating: rating)
  end

  def isprerequisite?(course1, course2)
    prerequisites.find_by_required_id_and_want_id(course2.id, course1.id)
  end

  def removeprerequisite!(course1, course2)
    prerequisites.find_by_required_id_and_want_id(course2.id, course1.id).destroy
  end

  def takingclass?(course)
    relationships.find_by_course_id(course.id)
  end

  def takeclass!(course)
    relationships.create!(course_id: course.id, prereqlevel: 40)
  end

  def removeclass!(course)
    relationships.find_by_course_id(course.id).destroy
  end

  def setup_prereqs
    require 'json'
    @program = self
    @courses = @program.courses
    @relationships = @program.prerequisites
    @allpre = @relationships
    @allrela = @program.relationships
    @allprer = []
    @nothingcourse = []
    @bottomcourse = []
    @topcourse = []
    @middlecourse = []
    @passedcourses = []
    @relation = []
    @connections = {}
    @relationships.each do |rel|
      @relation << [rel.want_id, rel.required_id, rel.id]
      if @connections[rel.want_id] == nil
        @connections[rel.want_id] = 1
      else
        @connections[rel.want_id] += 1
      end
      if @connections[rel.required_id] == nil
        @connections[rel.required_id] = 1
      else
        @connections[rel.required_id] += 1
      end
    end
    @courses.each do |course|
      @coursewant = []
      @courseneeded = []
      @relation.each do |rel|
        if rel[0] == course.id
          @coursewant << rel[1]
        end
        if rel[1] == course.id
          @courseneeded << rel[0]
        end
      end
      if @coursewant.count == 0
        if @courseneeded.count > 0
          @bottomcourse << course
        else
          @nothingcourse << course
        end
      end
      @coursewant.each do |prer|
        @course_pre = Course.find(prer)
        @allprer << [course, @course_pre]
      end
    end
    @courselevels = {}
    @coursele = {}
    def findlevels(bottom, number)
      bottom.each do |a|
        @level = number
        if @courselevels[a].nil? or @courselevels[a] < @level
          @courselevels.merge!(a => @level)
          @coursele.merge!(a.id => @level)
        end
        @under = Prerequisite.where("required_id = ?", a.id).where("wantpro_id = ?", @program.id)
        @underarray = []
        @under.each do |prereq|
          @underarray << Course.find(prereq.want_id)
        end
        findlevels(@underarray, @level+1)
      end
    end
    findlevels(@bottomcourse, 0)
    def findtoplevel(pre)
      @lowest = 40
      @allprer.each do |each|
        @eee = each[0]
        if each[1].id == pre.id
          if (@coursele[@eee.id] - 1) < @lowest
            @lowest = @coursele[@eee.id] - 1
          end
        end
      end
      if @lowest != 40
        @courselevels[pre] = @lowest
      end
    end
    @bottomcourse.each do |prelev|
      findtoplevel(prelev)
    end
    @middlecourse.each do |prelev|
      findtoplevel(prelev)
    end
    @nothingcourse.each do |course|
      @rela = @allrela.find_by_course_id(course.id)
      @rela.prereqlevel = 40
      @rela.save
    end

    #### HERE

    @coursewidths = {}
    @levelcourses = {}
    @courselevels.each do |course, h|
      if @coursewidths.has_key?(h)
        @coursewidths[h]+=1
      else
        @coursewidths[h]=1
      end
      if @levelcourses.has_key?(h)
        @levelcourses[h] << course.id
      else
        @levelcourses[h] = [course.id]
      end
    end
    @maxwidth = 0
    @coursewidths[40]=0
    @coursewidths.each do |h, value|
      @coursewidths[h]-=1
      if value>@maxwidth
        @maxwidth = value
      end
    end

    @levelcourses.delete(40)
    @aaa = 0
    @optimal = {}
    @posi = {}
    @min = 100000

    def ww(a)
      @c2 = {}
      @levelcourses.each do |key, arr|
        @a = (@maxwidth-arr.length)/2
        arr.each do |cour|
          @c2[cour] = [key, @a+a[cour][1]]
        end
      end
      return @c2
    end

    def dis(a)
      @qqq = 0
      @c1 = ww(a)
      @allpre.each do |pre|
        first = pre.required_id
        sec = pre.want_id
        @qqq += (((@c1[first][0]-@c1[sec][0])**2)+((@c1[first][1]-@c1[sec][1])**2))**0.5
      end
      return @qqq
    end
    def dista (levels, row, col, c, p)
      if @min > 55
          if (row<levels.length-1)
            if (col<levels[row].length)
              @tem = c.clone
              c.each do |num|
                @tem.delete(num)
                @tem1 = p.clone
                @tem1[levels[row][col]] = [row, num]
              dista(levels, row, col+1, @tem, @tem1)
                @tem = c.clone
              end
              else
                @ar1 = []
              for i in 0..@levelcourses[row+1].length-1
              @ar1 << i
            end
                dista(levels, row+1, 0, @ar1, p)
              end
            else
              if (col<levels[row].length)
              @tem = c.clone
              c.each do |num|
                @tem.delete(num)
                @tem1 = p.clone
                @tem1[levels[row][col]] = [row, num]
              dista(levels, row, col+1, @tem, @tem1)
                @tem = c.clone
              end
              else
                @zz = dis(p)
                if @zz < @min
                  @min = @zz
                  @optimal = p.clone
                end
              end
          end
        end
      end

      @min1 = 10000

      def neighbors (levels, current, p)
        levels.each do |ll, l|
          if l.length != 1
            l.each do |l1|
              if Random.rand(@connections[l1]) >= 2
                l.each do |l2|
                  if l2>l1
                    @temp1 = p.clone
                    @temp2 = @temp1[l1].clone
                    @temp1[l1] = @temp1[l2].clone
                    @temp1[l2] = @temp2.clone
                    @a1 = dis(@temp1)
                    if @a1 < current
                      if @min > @a1
                        @min = @a1
                        @optimal = @temp1.clone
                      end
                      neighbors(levels, @a1, @temp1)
                    end
                  end
                end
              end
            end
          end
        end
      end
    @ar = []

    if(!(@levelcourses.length == 0))
      for i in 0..@levelcourses[0].length-1
        @ar << i
      end
      dista(@levelcourses, 0, 0, @ar, @posi)
    end
    neighbors(@levelcourses, @min, @optimal)
    @optimal.each do |k, v|
      @rela = @allrela.find_by_course_id(k)
      @rela.prereqpos = v[1]
      @rela.prereqlevel = v[0]
      @rela.save
    end
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
	before_filter :signed_in_user
	before_filter :correct_user, only: [:edit, :update, :destroycourse]
	before_filter :correct_user_add, only: :addcourses
	before_filter :program_des, only: :destroy

	def new
		@user = User.find_by_remember_token(cookies[:remember_token])
    	@program = current_user.programs.build if signed_in?
	end

	def create
        @program = current_user.programs.build(params[:program])
        if @program.save
          countcat(params[:program][:category])
          redirect_to program_path(@program)
        else
          render 'new'
        end
	end

	def prereq_tree
		require 'json'
		@program = Program.find(params[:id])
		@allrela = @program.relationships
		@allpre = @program.prerequisites
		@courses = @program.courses
		@courselevels = {}
		@nothingcourse = []
		@doneunder = []
		@passedcourses = []
		@coursestop = {}
		@coursesbottom = {}
		@relation = []
		@connections = {}
		@allrela.each do |rel|
			@courselevels[Course.find(rel.course_id)] = rel.prereqlevel
			if rel.prereqlevel == 40
				@nothingcourse << Course.find(rel.course_id)
			end
		end
		@allpre.each do |pre|
			if @coursestop[pre.required_id].nil?
				@coursestop[pre.required_id] = [pre.want_id]
			else
				@coursestop[pre.required_id] << pre.want_id
			end
			if @coursesbottom[pre.want_id].nil?
				@coursesbottom[pre.want_id] = [pre.required_id]
			else
				@coursesbottom[pre.want_id] << pre.required_id
			end
			@relation << [pre.want_id, pre.required_id]
			if @connections[pre.want_id] == nil
				@connections[pre.want_id] = 1
			else
				@connections[pre.want_id] += 1
			end
			if @connections[pre.required_id] == nil
				@connections[pre.required_id] = 1
			else
				@connections[pre.required_id] += 1
			end
		end
		@courses.each do |course|
	        if current_user.passedcourse?(current_user, course)
	        	@passedcourses << course.id
	        end
	    end
		@courses.each do |course|
	        if !@passedcourses.include?(course.id)
	        	@coursewant = []
	        	@courseneeded = []
	        	@relation.each do |rel|
	        		if rel[0] == course.id
	        	    	@coursewant << rel[1]
	        		end
	        		if rel[1] == course.id
	        	  		@courseneeded << rel[0]
	        		end
	        	end
	        	if @coursewant.count > 0
		        	@howmany = 0
		        	@coursewant.each do |prer|
		        	    if @passedcourses.include?(prer)
		        	    	@howmany += 1
		        	    end
		        	end
		        	if @howmany == @coursewant.count
		        	    @doneunder << course.id
		        	end
		    	else
		    		@doneunder << course.id
		    	end
		    end
	    end
		@highestlevel = 0
		@courselevels.each do |key, value|
			if value > @highestlevel and value != 40
				@highestlevel = value
			end
		end
		@allprereqs = []
		@courses.each do |course|
			@coursewant = []
			@relation.each do |rel|
				if rel[0] == course.id
					@coursewant << rel[1]
				end
			end
			@coursewant.each do |prer|
				@first = "#" + course.id.to_s
				@second = "#" + prer.to_s
				@allprereqs << [@first, @second]
			end
		end

		@levelcourses = {}
		@optimal = {}
		@courselevels.each do |course, h|
			if @levelcourses.has_key?(h)
				@levelcourses[h] << course.id
			else
				@levelcourses[h] = [course.id]
			end
			@temp11 = Relationship.find_by_program_id_and_course_id(@program.id, course.id)
			@optimal[course.id] = [@temp11.prereqlevel, @temp11.prereqpos]
		end

		@layers = []
		@lays = []
		
		if (!(@highestlevel==0))
			for i in 0..@highestlevel do
				for j in 0..@levelcourses[i].length-1 do
					if @layers[i] == nil
						@layers[i] = [Course.find(@optimal.invert[[i,j]])]
					else
						@layers[i] << Course.find(@optimal.invert[[i,j]])
					end
				end
				@lays << (@highestlevel-i)
			end
		end
	end

	def index
		@programs = Program.order("rating_algo DESC").all
	end

	def prerequisites
		@program = Program.find(params[:id])
		@course = @program.courses.all
	end

	def removeprerequisites
		@program = Program.find(params[:id])
		@course = @program.courses.all
	end

	def show
		@program = Program.find(params[:id])
		@rating = Programrating.new
		@review = Programrating.new
		@cours_items = @program.courses.all
		@hasreview = Programrating.where("program_id = ?", @program.id).where("user_id = ?", current_user.id).where("review_title IS NOT NULL")
		@programratings = Programrating.where("program_id = ?", @program.id).where("rating IS NOT NULL")
		@programreviews = Programrating.where("program_id = ?", @program.id).where("review_title IS NOT NULL")
		@averagerating = "0"
		@total_course = 0
		@cours_items.each do |course|
			@status = Completecourse.find_by_course_id_and_user_id(course.id, current_user.id)
			if !@status.nil?
				if @status.passed
					@total_course += 1
				end
			end
		end
		if !@cours_items.nil?
			if @cours_items.count > 0
				@progress = ((@total_course.to_f/@cours_items.count.to_f)*100).round
				@progress_width = 100-@progress
			end
		end
		if @programratings.any?
			if @program.average_rating != 0
				@num_rates = @program.num_rating
				@averagerating = @program.average_rating
				@good_starwidth = (@averagerating.to_f/0.05).to_f.to_s + "%"
				@anti_starwidth = (((1-(@averagerating.to_f/5))*100).to_f).to_f.to_s + "%"
			end
		end
	end

	def edit
		@program = Program.find(params[:id])
		@courses = @program.courses
	end

	def update
		@program = Program.find(params[:id])
		if @program.update_attributes(params[:program])
			countcat(params[:program][:category])
			render "program_edit_js"
		else
			render "program_edit_js"
		end
	end

	def addcourses
		if !params.has_key?(:program)
			redirect_to "/creations"
		elsif params[:program].nil?
			redirect_to "/creations"
		end
		@courses = Course.all
		@carts = Cart.where("follower_id = ?", current_user.id)
		@program = Program.find(params[:program])
	end

	def destroycourse
		@program = Program.find(params[:course][:program])
		@course = Course.find(params[:course][:course])
		@courses = @program.courses
		@program.removeclass!(@course)
		render :template => "programs/course_move_js", :locals => {:@courses => @courses}
	end

	def destroy
		@program = Program.find(params[:id])
		@program.destroy
		redirect_to '/creations'
	end

	private

		def countcat(cat)
			@num = Program.where("category = ?", cat)
			@count = @num.count
			@cat = Category.find(cat)
			@cat.numprog = @count
			@cat.save
		end

		def program_des
			redirect_to root_path unless progcreator?
		end

		def is_admin
			redirect_to root_path unless is_admin?
		end

		def signed_in_user
			redirect_to root_path, notice: "Please sign in." unless signed_in?
		end

		def correct_user_add
			@user = User.find(Program.find(params[:program]).user_id)
			redirect_to(root_path) unless current_user?(@user)
		end

		def correct_user
			@user = User.find(Program.find(params[:id]).user_id)
			redirect_to(root_path) unless current_user?(@user)
		end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_add_registration.html.erb
<% if !current_user.registered?(@program) %>
	<%= form_for(current_user.registrations.build(takenprog_id: @program.id), :remote => true) do |f| %>
	  	<%= f.hidden_field :takenprog_id %>
	  	<%= f.hidden_field :in_course, :value => "0" %>
	  	<%= f.submit "Register", :class => "reg-btn reg-btn-add" %>
	<% end %>
<% else %>
	<%= form_for(current_user.registrations.find_by_takenprog_id(@program.id), 
				 html: { method: :delete }, :remote => true) do |f| %>
	  <div><%= f.hidden_field :takenprog_id %></div>
	  <%= f.submit "Unregister", :class => "reg-btn reg-btn-rem" %>
	<% end %>
<% end %>

app/views/programs/_course_list.html.erb
<% @courses.each_with_index do |course, i| %>
	<div>
		<span class="content">
			<%= form_for(course, :remote => true) do |f| %>
		  		<%= f.hidden_field :move, :value => "1" %>
		  		<%= f.hidden_field :program, :value => @program.id %>
		  		<%= f.hidden_field :course, :value => course.id %>
		  		<%= f.submit "", :type => :image, :src => "/assets/arrow-up.png", :class => "list_arrow1" %>
			<% end %>
			<%= form_for(course, :remote => true) do |f| %>
		  		<%= f.hidden_field :move, :value => "0" %>
		  		<%= f.hidden_field :program, :value => @program.id %>
		  		<%= f.hidden_field :course, :value => course.id %>
		  		<%= f.submit "", :type => :image, :src => "/assets/arrow-down.png", :class => "list_arrow1" %>
			<% end %>
			<%= i+1 %>.
			<%= link_to course.title, course_path(course, :program => @program.id) %>
			<span class="delete-btn-div">
			<%= form_for(course, remote: true, :url => { :action => 'destroycourse' }) do |f| %>
		  		<%= f.hidden_field :program, :value => @program.id %>
		  		<%= f.hidden_field :course, :value => course.id %>
		  		<%= f.submit "Remove", :class => "delete_btn_c" %>
			<% end %>
			</span>
		</span>
	</div>
<% end %>

app/views/programs/_program_form.html.erb
<%= form_for(@program, :remote => true) do |f| %>
<%= render 'shared/error_messages', object: f.object, :html => { :id => "myform" } %>
	<div>
		<%= f.label "Program Title :" %>
	<span>
		<%= f.text_field :title %>
	</span>
	</div>
	<div>
		<%= f.label "Short Description :" %>
	<span>
		<%= f.text_area :short_desc %>
	</span>
	</div>
	<div>
		<%= f.label "Full Description :" %>
	<span>
		<%= f.text_area :description %>
	</span>
	</div>
	<div>
		<%= f.label "Program Category :" %>
		<%= f.select :category, Category.order_by('title ASC').all.collect {|category| [ category.title, category.id ] } %>
	</div>
	<div><%= f.submit "Update Program Info", class: "subcon", :disable_with => "Updating…" %></div>
<% end %>

app/views/programs/_progress_partial.html.erb
<% if !@cours_items.nil? and current_user.registered?(@program) %>
	<div class="exams-container">
		<div id="cou-title">
			PROGRESS REPORT
		</div>
		<div class="files-bar"></div>
		<div>&nbsp</div>
		<div class="progress">
			<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<%=@progress%>" aria-valuemin="0" aria-valuemax="100" style="width: <%=@progress%>%">
				<span class="sr-only">40% Complete (success)</span>
			</div>
		</div>
			Completed <%= @total_course %> of <%= @cours_items.count %> courses.
		</div>
	</div>
<% end %>

app/views/programs/_reviews_partial.html.erb
<% if !current_user.registered?(@program) %>
	<div class="reviews-container">
		<div class="reviews">
			<span class="file-upload">
				<span>Program Reviews</span>
			</span>
		</div>
		<div class="files-bar"></div>
		<div class="course-rating-cont">
			<% if @averagerating == "0" %>
				<div class="course-rating-title">No Ratings Yet | </div>
			<% else %>
				<div class="course-rating-title">
					<span class="star-title">Average Rating: </span>
					<span class="star-cont">
						<span class="star" style="width:<%= @good_starwidth %>">★★★★★</span>
						<span class="anti-star" style="width:<%= @anti_starwidth %>"><span class="star-right">☆☆☆☆☆</span></span>
					</span>
					<span class="star-title">(<%= pluralize(@num_rates, "rating")%>)</span> | </div>
			<% end %>
			<div class="course-rating">
				<%= form_for @rating do |f| %>
					<%= f.radio_button :rating, "1" %> <%= f.label :rating, "1" %>
					<%= f.radio_button :rating, "2" %> <%= f.label :rating, "2" %>
					<%= f.radio_button :rating, "3" %> <%= f.label :rating, "3" %>
					<%= f.radio_button :rating, "4" %> <%= f.label :rating, "4" %>
					<%= f.radio_button :rating, "5" %> <%= f.label :rating, "5" %>
					<%= f.hidden_field :id, :value => params[:id] %>
					<%= f.submit "Rate Program!"%>
				<% end %>
			</div>
		</div>
		<div class="review-text">
			<ul class="review-list">
				<% @programreviews.each do |review| %>
					<li>
						<h4>
							<% if !(review.rating.nil?) %>
								<% @good_starwidth_person = (review.rating/0.05).to_f.to_s + "%" %>
								<% @anti_starwidth_person = ((5-review.rating)/0.05).to_f.to_s + "%" %>
								<span class="star-cont">
									<span class="star" style="width:<%= @good_starwidth_person %>">★★★★★</span>
									<span class="anti-star" style="width:<%= @anti_starwidth_person %>">
										<span class="star-right">☆☆☆☆☆</span>
									</span>
								</span>
							<% else %>
								No rating
							<% end %>
							<%= review.review_title %> <span id="reviewer-name"> By <%= review.user.name %></span>
						</h4>
						<span id="reviewer-content"><%= review.review_content %></span>
					</li>
				<% end %>
			</ul>
			<div>
				<%= form_for @review do |f| %>
					<div>
						<%= f.label :review_title, "Review Title :" %>
						<%= f.text_field :review_title %>
					</div>
					<div id="review-box-cont">
						<div><%= f.label :review_content, "Review :" %></div>
						<div><%= f.text_area :review_content, :id => "review-box"%></div>
					</div>
					<%= f.hidden_field :id, :value => params[:id] %>
					<%= f.submit "Submit Review"%>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

app/views/programs/course_move_js.js.erb
$("#course_list_id").html("<%= escape_javascript (render :partial => 'programs/course_list' ) %>");

app/views/programs/edit.html.erb
<% provide(:title, "Edit Program") %>
<h1>
	<%= @program.title %><span class="edit-title-course"><%= link_to "Return to program", program_path(@program) %></span>
</h1>
<% if params.has_key?(:errors) %> 
	<div class="error_explanation">
		<div class="alert alert-error">
			<% if params.has_key?(:youtuber) %>
				The video form contains <%= pluralize(params[:errors].count, "error") %>.
			<% else %>
				The file form contains <%= pluralize(params[:errors].count, "error") %>.
			<% end %>
		</div>
		<ul>
			<% params[:errors].each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<div class="course-edit-form-cont">
	<div id="program_form_edit">
	<%= render "program_form" %>
	</div>
</div>
<div>
<span> Courses 
	<%= link_to "Add", addcourses_path(:program => params[:id]), :class => "prereq-style" %>
	<span>
		<%= link_to "Set up prerequisites", {controller: "programs", action: "prerequisites", :id => "#{@program.id}"}, {:class => "prereq-style"} %>
	</span>
	<span>
		<%= link_to "Remove prerequisites", {controller: "programs", action: "removeprerequisites", :id => "#{@program.id}" },  {:class => "prereq-style"} %>
	</span>
</span>
<div class="course-edit-bar"></div>
<ul class="notes">
	<div id="course_list_id">
		<%= render "course_list" %>
	</div>
</ul>
</div>

app/views/programs/index.html.erb
<% provide(:title, "All Programs") %>
<div class="courses">
<h1>Here's a list of all programs!</h1>
<p>Sorted: rating algo</p>
<% @programs.each do |program| %>
	<%= link_to(program_path(program)) do %>
	<div class="course-list">
		<div class="category-image">
			<% if !Category.find_by_id(program.category).nil? %>
				<img src="data:<%= Category.find_by_id(program.category).imagetype %>;base64,<%= Category.find_by_id(program.category).image.to_s %>" />
			<% end %>
		</div>
		<div class="cours-list-cont">
			<div class="cours-top">
				<span class="courstitle-list">
					<%= program.title %>
				</span>
				<span class="smaller">
					By <%= User.find_by_id(program.user_id).name %>
				</span>
			</div>
			<div class="cours-middle"><%= program.short_desc %></div>
			<div class="cours-stats">
				<span>
					Courses: <%= program.courses.count %> &nbsp &nbsp Students: <%= program.numstudents %> &nbsp &nbsp Rating:
				</span>
				<span class="list-star">
					<% if program.average_rating == 0 %>
						Not rated
					<% else %>
						<span><%= program.average_rating %> stars (<%= program.num_rating%>)</span>
					<% end %>
				</span>
			</div>
		</div>
	</div>
	<% end %>
<% end %>
</div>

app/views/programs/show.html.erb
<% provide(:title, @program.title) %>
<div class="course-show">
	<div class="course-info">
		<h1>
			<%= @program.title %><span class="smaller"> By <%= @program.user.name %></span>
		</h1>
		<div id="class-des">
			<%= @program.description %>
		</div>
	</div>
	<div class="course-btns">
		<div id="prog_registration">
			<%= render 'add_registration' %>
		</div>
		<% if progcreate %>
			<div class="edit-cont">
				<div class="edit-btn profile-btn">
					<%= link_to "Edit", edit_program_path(@program) %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="files-container">
		<div id="cou-title">
			COURSES <%= link_to "Prerequisite Tree", prereq_tree_program_path(@program) %>
		</div>
		<div class="files-bar"></div>
		<ul class="prog-cours-list">
		<% if @cours_items.any? %>
			<% @cours_items.each do |cours| %>
				<li><%= link_to cours.title, course_path(cours, :program => @program.id) %></li>
			<% end %>
		<% end %>
		</ul>
	</div> 
	<div id="load_progress">
		<%= render 'progress_partial' %>
	</div>
	<div id="load_reviews">
		<%= render 'reviews_partial' %>
	</div>
</div>