config/routes.rb
LearnApp::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :admin
  resources :relationships, only: [:create, :destroy, :index]
  resources :carts, only: [:create, :destroy]
  resources :prerequisites, only: :create
  resources :registrations, only: [:create, :destroy]
  resources :courseregistrations, only: [:create, :destroy]
  resources :exams
  resources :questions
  resources :answers
  resources :examresults
  resources :courseratings
  resources :programratings
  resources :categories
  resources :courses do
    member do
      get :programs, :followers, :wants, :wantpros, :notes, :newexam
    end
  end
  resources :users do
    member do
      get :takenprogs, :students, :coursefollows
    end
  end
  resources :programs do
    member do
      get :courses, :wants, :required_courses, :students, :prereq_tree
      put :destroycourse
    end
    collection do
      get :prerequisites, :removeprerequisites
    end
  end
  resources :notes do
    member {get 'download'}
  end

  root to: "static_pages#home"
  match '/admin/add_number', to: "admin#add_number"
  match '/numberusers',   to: "static_pages#latest_number_users"
  match '/addcourses',    to: "programs#addcourses"
  match '/viewfile',      to: "notes#view"
  match '/passcourse',    to: "courses#passcourse"
  match '/moveupcourse',  to: "courses#listorder_up"
  match '/movedowncourse',to: "courses#listorder_down"
  match '/moveupexam',    to: "exams#listorder_up"
  match '/movedownexam',  to: "exams#listorder_down"
  match '/cart',          to: "users#cart"
  match '/programs',      to: "programs#index"
  match '/newprogram',    to: "programs#new"
  match '/newexam',       to: "exams#new"
  match '/courses',       to: "courses#index"
  match '/creations',     to: "users#creations"
  match '/newcourse',     to: "courses#new"
  match '/search',        to: "search#index"
  match '/database',      to: "admin#database"
  match '/addcategory',   to: "admin#addcategory"
  match '/signup',        to: "users#new"
  match '/signin',        to: "sessions#new"
  match '/signout',       to: "sessions#destroy", via: :delete
  match '/about',         to: "static_pages#about"
  match '/help',          to: "static_pages#help"
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :image, :title, :imagetype, :numprog, :numcour

  scope :order_by, lambda { |o| {:order => o} } 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_filter :admin_user, only: [:create, :destroy, :edit, :update]
	def create
		@image = Base64.encode64(open(params[:category][:image].tempfile).to_a.join)
		Category.create!(:title => params[:category][:title], :image => @image, :imagetype => params[:category][:image].content_type)
	  	redirect_to database_path
	end

	def update
		@cat = Category.find(params[:id])
		if params[:category].has_key?(:image)
			@image = Base64.encode64(open(params[:category][:image].tempfile).to_a.join)
			@cat.update_attributes(:title => params[:category][:title], :image => @image, :imagetype => params[:category][:image].content_type)
		else
			@cat.update_attributes(:title => params[:category][:title])
		end
		redirect_to database_path
	end

	def edit
		@cat = Category.find(params[:id])
	end

	def destroy
    	Category.find(params[:id]).destroy
    	redirect_to database_path
  	end

  	def show
  		@cat = Category.find(params[:id])
  		@programs_1 = Program.where("category = ?", @cat.id)
  		@courses_1 = Course.where("category = ?", @cat.id)
  		@prog_size = @programs_1.size
  		@cour_size = @courses_1.size
  		@programs = @programs_1.first(4)
  		@courses = @courses_1.first(4)
  	end

	private
    	def admin_user
    		redirect_to(root_path) unless current_user.admin?
    	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>
<%= form_for(@cat) do |f| %>
		<div>
			<%= f.label :title %> :
			<%= f.text_field :title %>
		</div>
		<div>
			<%= f.label :image %> :
			<%= f.file_field :image %>
		</div>
		<div>
			<%= f.submit "Create Category", class: "subcon" %>
		</div>
	<% end %>

app/views/categories/show.html.erb
<% provide :title, @cat.title %>
<h1>
	<%= @cat.title %>
	<div class="edit-title-course">
		<%= link_to "Return to all categories", root_path %>
	</div>
</h1>
<div class="cat-lists">
	<h1>PROGRAMS</h1>
	<% if @prog_size > 0 %>
		<div class="cat-list-cont">
		<% @programs.each do |prog| %>
			<%= link_to program_path(prog) do %>
			<div>
				<div><%= prog.title %></div>
				<div>By <%= User.find(prog.user_id).name %></div>
				<div class="list-star">
					<% if prog.average_rating == 0 %>
						Not rated
					<% else %>
						<%= prog.average_rating %> stars (<%= prog.num_rating%>)
					<% end %>
				</div>
			</div>
			<% end %>
		<% end %>
		<% if @prog_size > 4 %>
			<div class="see_all_link">See all</div>
		<% end %>
		</div>
	<% else %>
		There aren't any programs in this field yet.
	<% end %>
</div>
<div class="cat-lists">
	<h1>COURSES</h1>
	<% if @cour_size > 0 %>
		<div class="cat-list-cont">
		<% @courses.each do |course| %>
			<%= link_to course_path(course) do %>
			<div>
				<div><%= course.title %></div>
				<div>By <%= User.find(course.user_id).name %></div>
				<div class="list-star">
					<% if course.average_rating == 0 %>
						Not rated
					<% else %>
						<%= course.average_rating %> stars (<%= course.num_rating%>)
					<% end %>
				</div>
			</div>
			<% end %>
		<% end %>
		<% if @cour_size > 4 %>
			<div class="see_all_link">See all</div>
		<% end %>
		</div>
	<% else %>
		There aren't any programs in this field yet.
	<% end %>
</div>